# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b9ff789561f504fe5ff2028f4bb8ef86a2b17c8d21d5eeb6bdc680f2295b4ee26742b14edb42bbf1138dcd07546938d6fd3196f4e08354058a7492dd9161c6c

test:
  secret_key_base: a1cb5b6009bfa65f785bf78190d8df0a315159ffd30049558cfdc2d6120695a6cc2807562f15f08297e3a9b20b4463fbf970af838ae677849580af927c21bf3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
